---
- name: Update package lists
  apt: update_cache=yes

- name: Install packages
  apt: name={{  item  }}  state=latest
  with_items: packages

- name: Activate Apache2 mod
  command: /usr/sbin/a2enmod {{ item  }}
  with_items: a2enmods

- name: Disable default site
  command: /usr/sbin/a2dissite 000-default

- name: Change default page
  copy: src=/etc/ansible/roles/seedbox/files/index.html dest=/var/www/html/index.html owner=www-data group=www-data mode=644

- name: Clone rutorrent
  command: git clone https://github.com/Novik/ruTorrent.git /var/www/html/rutorrent

- name: Add conf file for rutorrent -- torrents creation
  copy: src=/etc/ansible/roles/seedbox/files/conf.php dest=/var/www/html/rutorrent/plugins/create/conf.php owner=www-data group=www-data mode=644

- name: Change apache2.conf
  copy: src=/etc/ansible/roles/seedbox/files/apache2.conf dest=/etc/apache2/apache2.conf owner=root group=root mode=644

- name: Copy rutorrent .htaccess
  copy: src=/etc/ansible/roles/seedbox/files/.htaccess dest=/var/www/html/ruttorent/.htaccess owner=www-data group=www-data mode=644
