---
- name: Update package lists
  apt: update_cache=yes

- name: Install packages
  apt: name={{  item  }}  state=latest
  with_items: packages

- name: Activate Apache2 mod
  command: /usr/sbin/a2enmod {{ item  }}
  with_items: a2enmods
