---
- name: Update package lists
  apt: update_cache=yes

- name: Install packages
  apt: name={{  item  }}  state=latest
  with_items: packages

- name: Activate Apache2 mod
  command: /usr/sbin/a2enmod {{ item  }}
  with_items: a2enmods

- name: Disable default site
  command: /usr/sbin/a2dissite 000-default

- name: Change default page
  copy: src=/etc/ansible/roles/seedbox/files/index.html dest=/var/www/html/index.html owner=www-data group=www-data mode=644
